swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /categories:
    get:
      tags:
        - Categories
      summary: Retrieve all categories
      description: Returns a list of all categories
      produces:
        - application/json
      responses:
        '200':
          description: List of categories
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 1
                name:
                  type: string
                  example: "Objets"
        '500':
          description: Internal Server Error
  /user/accounts:
    get:
      tags:
        - Accounts
      summary: Retrieve all accounts
      description: Returns a list of all accounts for the logged-in user
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        '200':
          description: List of accounts
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions:
    parameters:
      - name: accountId
        in: path
        required: true
        type: string
        description: ID of the account
    get:
      tags:
        - Transactions
      summary: Retrieve all transactions for an account
      description: Returns a list of all transactions for the specified account
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        '200':
          description: List of transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionId}:
    parameters:
      - name: accountId
        in: path
        required: true
        type: string
        description: ID of the account
      - name: transactionId
        in: path
        required: true
        type: string
        description: ID of the transaction to retrieve
    get:
      tags:
        - Transactions
      summary: Retrieve a transaction
      description: Returns a specific transaction by ID
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction not found
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transactions
      summary: Update a transaction
      description: Update note and categories of a specific transaction by ID
      parameters:
        - in: body
          name: body
          description: Partial Transaction Payload
          required: true
          schema:
            $ref: '#/definitions/UpdateTransaction'
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Account:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the account
      title:
        type: string
        description: Title of the account
      amount:
        type: string
        description: Balance amount
      description:
        type: string
        description: Description of the account balance
    example:
      id: "ac_1234567890"
      title: "Argent Bank Checking (x8349)"
      amount: "$2,082.79"
      description: "Available Balance"
  Transaction:
    type: object
    properties:
      id:
        type: string
      amount:
        type: number
      type:
        type: string
      categories:
        type: array
        items:
          type: string
      date:
        type: string
      description:
        type: string
      balance:
        type: number
        format: float
        description: Account balance after the transaction
      note:
        type: string
    example:
      id: "tr_1234567890"
      amount: 8.00
      type: "Electronic"
      categories: ["Food"]
      date: "2020-02-27"
      description: "Golden Sun Bakery"
      balance: 298.00
      note: "Note about the transaction"
  UpdateTransaction:
    type: object
    properties:
      note:
        type: string
      categories:
        type: array
        items:
          type: string
    example:
      note: "Updated note about the transaction"
      categories: ["Updated Category"]
